### PR TITLE
Rails 5+ Support

### PR DESCRIPTION
**Pull request by molawson**
### Background

My company has been using demoji for a while in production.  We're currently upgrading a few apps to Rails 5.0 and 5.1.  The Rails team deprecated (in 5.0) and removed support (in 5.1) for `alias_method_chain`, pushing app and library authors towards `Module.prepend` instead.

### Changes

This PR is an attempt to move demoji in that direction, as well.

In doing so, I added a couple of support commits to run on Ruby 2.x and remove deprecations from RSpec.

### Feedback

Does this seem like a direction you'd like to go?  Is there anything you'd change about the approach or implementation?

Thanks for this gem and taking time to look over these changes.

### CODE REVIEW

**Comment by davidjairala** [comment]
@molawson Thank you for the PR.  It's actually been in my list of things to do for this gem.

The approach is basically what I had in mind.  My only q would be around maybe bumping the ruby version all the way to 2.4.1 to see how it handles it?

**Comment by davidjairala** [comment]
Also interesting to note that this would break compatibility.  Might be OK if we tag with major version change.

**Comment by molawson** [comment]
@davidjairala I've bumped ruby-version to 2.4.1.  Everything seems to be working just fine (i.e. tests are passing).

Good point about this breaking installs with using older Ruby versions (< 2.0).  A major version bump seems like a great idea!

**Comment by davidjairala** [comment]
Thanks @molawson I'll check it out tomorrow morning and tag it if everything works well.

**Comment by davidjairala** [comment]
@molawson was noodling about this, and came up with this suggestion:
https://github.com/taskrabbit/demoji/pull/7

Basically the same, but keeps compatibility with 1.9.

What do you think?

**Comment by molawson** [comment]
@davidjairala That approach works great for me!  Going with `alias_method` to maintain backwards compatibility makes a ton of sense.  👍

**Pull request closed without merging**
