### PR TITLE
Dont alter binary datatype columns

### PR DESCRIPTION
**Pull request by thathoo**
Using demoji we were seeing issues with data in one of the table's binary columns being double encoded - this should fix that.

### CODE REVIEW

**Comment by davidjairala** [comment]
Thanks for the PR @thathoo . I've added a commit to master to make tests run again. Can you try that commit and add a test for this use case please?

**Comment by davidjairala** [comment]
Looks solid but looks like it could use a rebase.

**Comment by thathoo** [comment]
@davidjairala ah yes, sorry just rebased and squashed commits.

**Comment by davidjairala** [comment]
Looks good. Will merge and tag tomorrow morning. Thanks again.

**Pull request merged**
